---
title: "Ls1-4 data.table package"
output: html_document
---

## data.table

* Inherets from data.frame
  - All function that accept data.frame work on data.table
* Written in C so it's much faster
* Much, much faster at subsetting, group, and updating
```{r}
library(data.table)
DF = data.frame(x = rnorm(9), y=rep(c("a","b","c"),each = 3), z = rnorm(9))
head(DF,3)
DT = data.table(x = rnorm(9), y=rep(c("a","b","c"),each = 3), z = rnorm(9))
head(DT,3)
#To see all the data tables in memory, use tables()
tables()
DT[2,]
DT[DT$y=="a",]
#when subseting rows
DT[c(2,3)]
#One major difference between data.frame and data.table:
DT[,c(2,3)]
```


## Column subsetting in data.table


```{r}
{
  x=1
  y=2
}
DT[,list(mean(x),sum(z))]

DT[, table(y)]
```


## Adding a new column

```{r}
DT[,w:=z^2]

#One thing to be careful:
DT2<-DT
DT[,y:=2]
head(DT,n=3)
head(DT2,n=3)
#The y column in DT2 also changed after the y values in DT was changed.
#So if a backup copy is needed, make sure to use the copy function.
```


## Multiple operations

```{r}
DT[,m:={tmp<-(x+z);log2(tmp+5)}]
DT[,a:=x>0]
#For all rows with a as TRUE, b will be the mean value of x+w of A(TRUE).
DT[, b:=mean(x+w),by=a]
```

the last expression in {} will be passed to the assignment statement.


## Specieal variables

```{r}
set.seed(123);
#When facing large data table (with 100,000 rows):
DT<-data.table(x = sample(letters[1:3],1E5, TRUE))
DT[,.N, by=x]
# .N will count the number of each group divided by "by=x"
```
## Keys

```{r}
DT<-data.table(x = rep(c("a","b","c"),each=100), y=rnorm(300))
setkey(DT,x)
#After setting x as the key variable, then when asking for 'a', it went to look into x.
DT['a']
#using keys to join data
DT1<-data.table( x= c('a','a','b','dt1'), y=1:4)
DT2<-data.table( x= c('a','b','dt2'), z=5:7)
setkey(DT1,x);setkey(DT2,x)
merge(DT1,DT2)
```

## Fast Reading

```{r}
big_df<-data.frame(x=rnorm(1E6), y=rnorm(1E6))
file<-tempfile()
write.table(big_df, file = file, row.names = FALSE, col.names = TRUE, 
            sep = "\t",quote = FALSE)
system.time(fread(file))
system.time(read.table(file, header = TRUE, sep="\t"))
# fread is much faster than read.table
```

[what you can do with data frame that you can't in data table?](https://stackoverflow.com/questions/13618488/what-you-can-do-with-a-data-frame-that-you-cant-with-a-data-table)
